src/objects/Slack_Slash_Command__e.object
<CustomObject>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Slash_Command__c</fullName>
        <label>Slash Command</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Slack Slash Command</label>
    <pluralLabel>Slack Slash Commands</pluralLabel>
</CustomObject>

src/classes/SlackSlashCommandHandler.cls
public with sharing class SlackSlashCommandHandler {

    public static void handleSlashCommands(List<Slack_Slash_Command__e> commands) {
        for (Slack_Slash_Command__e c: commands) {
            switch on c.Slash_Command__c {
                when '/dynamodal' {
                    handleDynaModal(c);
                }
            }
        }
    }

    public static void handleDynaModal(Slack_Slash_Command__e command) {
        SlackService.createDynaBlockModal(command.Payload__c);
    }


}